# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9021a025cd34965633e347093e36f22943dc86adc9c76c07231d4d3acefdfa797a499a992a75795077cd99279bda7446273ed5a446f1cc459636149342967667

test:
  secret_key_base: ae97ab35e6e613720d774f238a44308c5b68734e49980c8a9cc1c6e2c5a2cc53647b20c063224d54512574025e3d64734bbb29154bf2edfffa6990c171fc1867

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
